{% set name = "google-cloud-core" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a4fcb0e2fcfd4bfe963837fad6d10943754fd79c1a50097d68540b6eb3d67f35

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - google-api-core >=1.31.6,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - google-auth >=1.25.0,<3.0dev
    # grpc extra
    - grpcio >=1.38.0,<2.0.0dev

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - google.api_core.client_info
    - google.cloud.client
    - google.cloud.environment_vars
    - google.cloud.exceptions
    - google.cloud.operation
  commands:
    - pip check

about:
  home: https://github.com/googleapis/python-cloud-core
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'API Client library for Google Cloud: Core Helpers'
  description: This library is not meant to stand-alone. Instead it defines common helpers (e.g. base Client and Connection classes) used by all of the  google-cloud-*.
  doc_url: https://googleapis.dev/python/google-cloud-core/latest/
  dev_url: https://github.com/googleapis/python-cloud-core

extra:
  recipe-maintainers:
    - xylar
    - parthea
    - tswast
