travis:
  secure:
    BINSTAR_TOKEN: Kr+YMSem0GK/JCg0BRkEvk/lzfd5s/VjM0Cs9MAhl+P3aChF8S89nzRhCWT60MlME14M3u0SckCqX2SN6lCzlAKwDxdtRVb/LDYcLMBVMTBm+ppQqD8whbjvGQNqdkNSsmoizHgtEzLR8vraa3sDXNihcMPBqK5xkANTNrMmu1fWxLe44w58vDrhKQZhh/UX+RdbSjrtB+dnce7RS2j3xACv6m8IUzWHrv16Y+GVh+HUL+1ql8BF8sVYHsOms5i2gE7uHP1qtgHBg93hOZ0NSp5fmRRDRuSpRdSVShavNXhXPJ57F9ntwSArjc+mRtp3Ls0qUDhYn+XCpf0Gl1TX9LXAZSRB34+l3gNJxDHfceoFk2BhQZGjhPfTRh4UgCGOY4NNctJCfEddTTYAyPEb19/yxb4MxW4WEI18HMZXaGF98khdjjVTWwlDwtGGfPrsEwkwK5znT5SQcQ7qY11f/CotPKz1yGKdzC3Z+QJzgvJDgN8T45L9AHM7HIUbpcIYvDzfOZk9Bfa78tSZ8PcgFcGbXDxjIz8RGSh3j+MqSzHQ7j0fkmRS296HRT7/8eYRIOLP6eDBO82FM9acf+OLuXnq/b0GM1kh6Qx30j6opnL/cuT7eGvMbKkzGYwbKF9SE9MKaz81addaj0vN+wMLhFxs9yEaeiPFVfRtd5cs28Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
